import type { Metadata } from 'next';
import Link from 'next/link';
import { Breadcrumbs } from '../../components/Breadcrumbs';
import { PageHero } from '../../components/PageHero';
import { checklistLibrary, resourceLibrary, site } from '../../lib/content';

export const metadata: Metadata = { title: 'Resources & Checklists', description: 'View and download ICAI-compliant checklists and compliance guides from Minchala & Associates.' };

export default function ResourcesPage() {
  return <main id="main"><Breadcrumbs items={[{ label: 'Resources' }]} /><PageHero eyebrow="Resources & checklists" title="Practical compliance checklists for better preparation." description="Educational, mobile-friendly resources for taxpayers, founders and finance teams. These materials are general guidance and not professional advice." /><section className="section-pad"><div className="container"><div className="rounded-[2rem] border border-[#e8dcc4] bg-[#fffaf0] p-6 text-sm leading-7 text-slate-700 md:p-8"><strong className="text-[#0B2341]">Important disclaimer:</strong> {site.complianceLine} The checklists below are general educational guidance only and must be reviewed against facts, current law, due dates, portal records and engagement scope.</div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{checklistLibrary.map((item) => <article key={item.slug} className="luxury-card rounded-3xl p-7"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#C9A24A]">{item.category}</p><h2 className="display mt-3 text-3xl">{item.title}</h2><p className="mt-3 leading-7 text-slate-600">{item.summary}</p><ul className="mt-5 space-y-2 text-sm leading-6 text-slate-600">{item.items.slice(0, 3).map((point) => <li key={point} className="flex gap-2"><span className="text-[#C9A24A]">✓</span><span>{point}</span></li>)}</ul><div className="mt-6 flex flex-wrap gap-3"><Link className="button-secondary" href={`/resources/checklists/${item.slug}`}>View checklist</Link><a className="inline-flex rounded-full border border-slate-200 px-5 py-3 text-sm font-bold text-[#0B2341]" href={item.downloadHref} download>Download</a></div></article>)}</div><h2 className="display mt-16 text-4xl">Additional resource downloads</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{resourceLibrary.map((item) => <article key={item.href} className="luxury-card rounded-3xl p-7"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#C9A24A]">{item.type}</p><h3 className="display mt-3 text-3xl">{item.title}</h3><p className="mt-3 leading-7 text-slate-600">{item.description}</p><a className="mt-5 inline-flex font-bold text-[#C9A24A]" href={item.href} download>Download →</a></article>)}</div></div></section></main>;
}
