import type { Metadata } from 'next';
import { Faq } from '../../components/Faq';
import { PageHero } from '../../components/PageHero';
import { ethicsNotes, processSteps, values } from '../../lib/content';

export const metadata: Metadata = { title: 'About', description: 'Learn about Minchala & Associates, an independent chartered accountancy firm guided by integrity, confidentiality and technical rigour.' };

export default function AboutPage() {
  return <main id="main"><PageHero eyebrow="About" title="Professional insight. Responsible advice." description="We help clients maintain reliable finance operations, understand statutory obligations and make decisions with confidence." /><section className="section-pad"><div className="container grid gap-12 lg:grid-cols-2"><div><p className="eyebrow text-[#b99655]">Our approach</p><h2 className="section-title">Built around independence, diligence and clarity.</h2></div><div className="space-y-5 text-lg leading-9 text-slate-700"><p>Minchala & Associates serves businesses, institutions and individuals through professional work founded on technical competence and ethical practice.</p><p>Every engagement is scoped with attention to professional eligibility, confidentiality, independence considerations and the client’s specific facts.</p></div></div><div className="container mt-12 grid gap-4 md:grid-cols-2">{values.map((value) => <article key={value.title} className="luxury-card rounded-2xl p-6"><h3 className="display text-3xl">{value.title}</h3><p className="mt-3 text-slate-600">{value.text}</p></article>)}</div></section><section className="section-pad bg-[#0b2433] text-white"><div className="container"><p className="eyebrow text-[#d0ad68]">Method</p><h2 className="section-title max-w-4xl">A disciplined path from facts to action.</h2><div className="mt-10 grid gap-5 md:grid-cols-4">{processSteps.map((step) => <article key={step.title} className="rounded-3xl border border-white/10 p-6"><h3 className="display text-3xl">{step.title}</h3><p className="mt-3 text-sm leading-7 text-white/62">{step.text}</p></article>)}</div></div></section><section className="section-pad bg-white"><div className="container"><p className="eyebrow text-[#b99655]">ICAI Code of Ethics</p><h2 className="section-title max-w-4xl">Informational, responsible and non-solicitous communication.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{ethicsNotes.map((note) => <article key={note} className="rounded-2xl border border-slate-200 p-6 text-slate-700">{note}</article>)}</div></div></section><Faq /></main>;
}
