import Link from 'next/link';
import { AssetImage } from '../components/AssetImage';
import { Faq } from '../components/Faq';
import { ServiceGrid } from '../components/ServiceGrid';
import { clientSituations, complianceCalendar, firmTimeline, images, industries, insights, partners, processSteps, proofPoints, site, staffProfiles, teamGroups, values } from '../lib/content';

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'AccountingService',
  name: site.name,
  description: site.intro,
  areaServed: ['Bapatla', 'Guntur', 'Hyderabad', 'India'],
  email: site.email,
  url: site.url,
};

export default function Home() {
  return (
    <main id="main">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <section className="relative isolate overflow-hidden bg-[#061724] py-20 text-white md:py-28">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_80%_16%,rgba(208,173,104,.32),transparent_30%),linear-gradient(135deg,#061724,#0e3144)]" />
        <div className="container grid gap-12 lg:grid-cols-[1.02fr_.98fr] lg:items-center">
          <div className="reveal">
            <p className="eyebrow text-[#d0ad68]">Chartered Accountants · Bapatla · Guntur · Hyderabad</p>
            <h1 className="display mt-8 max-w-5xl text-6xl leading-[0.94] tracking-[-0.05em] md:text-8xl">Clarity in complexity. <span className="text-[#dfc380]">Confidence in every decision.</span></h1>
            <p className="mt-8 max-w-2xl text-lg leading-8 text-white/72">{site.intro}</p>
            <div className="mt-10 flex flex-wrap gap-4"><Link href="/contact" className="button-primary">Schedule a consultation</Link><Link href="/services" className="button-secondary">Explore services</Link></div>
            <p className="mt-6 max-w-2xl text-xs leading-6 text-white/48">{site.localSeo} {site.complianceLine}</p>
          </div>
          <div className="reveal rounded-[2rem] border border-white/10 bg-white/[0.04] p-3 shadow-2xl">
            <AssetImage {...images.hero} width={1200} height={900} className="h-auto w-full rounded-[1.5rem] object-cover" priority />
          </div>
        </div>
      </section>

      <section className="section-pad bg-white"><div className="container grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow text-[#b99655]">Google Business Profile</p><h2 className="section-title">Find Minchala & Associates on Google Maps.</h2><p className="mt-5 leading-8 text-slate-600">Use the Google Business Profile link, directions route and firm-only contact details for appointment-based coordination with the Bapatla head office and Guntur / Hyderabad branches.</p><div className="mt-7 flex flex-wrap gap-3"><a className="button-primary" href={site.googleBusinessProfileHref} target="_blank" rel="noopener noreferrer">View on Google</a><a className="button-secondary" href={site.directionsHref} target="_blank" rel="noopener noreferrer">Get directions</a><a className="button-secondary" href={`tel:${site.phone.replace(/\s/g, '')}`}>Click to call</a></div><p className="mt-5 text-sm leading-7 text-slate-500">FRN {site.firmRegistrationNumber} · Head office: {site.headOffice} · Branch offices: {site.branchOffices.join(' and ')} · {site.email}</p></div><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-2xl shadow-slate-950/5"><iframe title="Google Maps location for Minchala & Associates" src={site.googleMapsEmbedSrc} className="h-[360px] w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></section>
      <section className="section-pad"><div className="container grid gap-5 md:grid-cols-3">{proofPoints.map((item) => <article key={item.label} className="luxury-card rounded-[1.75rem] p-7"><strong className="display text-5xl text-[#b99655]">{item.value}</strong><p className="mt-3 leading-7 text-slate-600">{item.label}</p></article>)}</div></section>
      <section className="section-pad bg-white"><div className="container grid gap-8 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow text-[#b99655]">Approved visual direction</p><h2 className="section-title">Navy, gold and white brand system with professional appointment pathways.</h2><p className="mt-5 leading-8 text-slate-600">The homepage uses the approved premium website mockup, corporate consultation CTA direction and firm-specific visual language without testimonials, ranking claims or aggressive solicitation.</p></div><div className="grid gap-5"><div className="luxury-card overflow-hidden rounded-[2rem] p-3"><AssetImage {...images.premiumMockup} width={1200} height={800} className="h-auto w-full rounded-[1.5rem] object-cover" /></div><div className="luxury-card overflow-hidden rounded-[2rem] p-3"><AssetImage {...images.corporateHome} width={1200} height={800} className="h-auto w-full rounded-[1.5rem] object-cover" /></div></div></div></section>
      <section className="section-pad bg-white"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#b99655]">The firm</p><h2 className="section-title">Independent advice for responsible leadership.</h2></div><div className="grid gap-4 sm:grid-cols-2">{values.map((value) => <article key={value.title} className="rounded-3xl border border-slate-200 p-6"><h3 className="display text-3xl">{value.title}</h3><p className="mt-3 leading-7 text-slate-600">{value.text}</p></article>)}</div></div></section>
      <section className="section-pad"><div className="container"><p className="eyebrow text-[#b99655]">Services</p><h2 className="section-title max-w-3xl">Integrated expertise across the finance and compliance lifecycle.</h2><div className="mt-12"><ServiceGrid /></div></div></section>
      <section className="section-pad bg-white"><div className="container"><p className="eyebrow text-[#b99655]">Industries served</p><h2 className="section-title max-w-4xl">Practical finance discipline for regional and growth-focused organizations.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{industries.map((item) => <article key={item.title} className="luxury-card rounded-3xl p-6"><h3 className="display text-3xl">{item.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{item.text}</p></article>)}</div></div></section>
      <section className="section-pad"><div className="container"><p className="eyebrow text-[#b99655]">Firm timeline</p><h2 className="section-title max-w-4xl">Built around professional standards, regional access and digital readiness.</h2><div className="mt-10 grid gap-5 md:grid-cols-4">{firmTimeline.map((item) => <article key={item.year} className="rounded-3xl border border-slate-200 bg-white p-6"><strong className="text-[#b99655]">{item.year}</strong><p className="mt-3 text-sm leading-7 text-slate-600">{item.text}</p></article>)}</div></div></section>
      <section className="section-pad bg-[#0b2433] text-white"><div className="container"><p className="eyebrow text-[#d0ad68]">Delivery model</p><h2 className="section-title max-w-4xl">Structured work, partner judgement and practical follow-through.</h2><div className="mt-12 grid gap-5 md:grid-cols-5">{processSteps.map((step, index) => <article key={step.title} className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><span className="text-[#d0ad68]">0{index + 1}</span><h3 className="display mt-4 text-3xl">{step.title}</h3><p className="mt-3 text-sm leading-7 text-white/62">{step.text}</p></article>)}</div></div></section>
      <section className="section-pad"><div className="container"><p className="eyebrow text-[#b99655]">Partners</p><h2 className="section-title max-w-4xl">Approved partner profiles and specialist delivery desks.</h2><div className="mt-12 grid gap-6 lg:grid-cols-2">{partners.map((partner) => <article key={partner.name} className="luxury-card overflow-hidden rounded-[1.75rem]"><AssetImage {...partner.image} width={900} height={600} className="h-64 w-full object-cover" /><div className="p-7"><h3 className="display text-3xl">{partner.name}</h3><p className="mt-1 text-sm font-bold uppercase tracking-[0.16em] text-[#b99655]">{partner.credentials} · {partner.role}</p><p className="mt-4 font-semibold text-[#0b2433]">{partner.focus}</p><p className="mt-3 leading-7 text-slate-600">{partner.bio}</p></div></article>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3">{staffProfiles.map((member) => <article key={member.name} className="rounded-3xl border border-slate-200 bg-white p-5"><AssetImage {...member.image} width={600} height={420} className="mb-4 h-40 w-full rounded-2xl object-cover" /><h3 className="display text-2xl">{member.name}</h3><p className="mt-1 text-xs font-bold uppercase tracking-[0.14em] text-[#b99655]">{member.role}</p><p className="mt-3 text-sm leading-7 text-slate-600">{member.bio}</p></article>)}</div><div className="mt-6 grid gap-4 md:grid-cols-4">{teamGroups.map((group) => <article key={group.title} className="rounded-3xl border border-slate-200 bg-white p-6"><h3 className="display text-2xl">{group.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{group.text}</p></article>)}</div></div></section>
      <section className="section-pad bg-white"><div className="container grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-[#b99655]">Client situations</p><h2 className="section-title">No testimonials. Only service contexts.</h2><p className="mt-5 leading-8 text-slate-600">To remain aligned with ICAI ethical requirements, this website does not publish client endorsements, rankings, superiority claims or guaranteed results.</p></div><div className="grid gap-4">{clientSituations.map((item) => <article key={item.title} className="rounded-3xl border border-slate-200 p-6"><h3 className="display text-3xl">{item.title}</h3><p className="mt-3 leading-7 text-slate-600">{item.text}</p></article>)}</div></div></section>
      <section className="section-pad"><div className="container grid gap-10 md:grid-cols-[0.8fr_1.2fr]"><div><p className="eyebrow text-[#b99655]">Knowledge Hub</p><h2 className="section-title">Current thinking, clearly structured.</h2></div><div className="space-y-4">{insights.map((item) => <article key={item.title} className="luxury-card rounded-2xl p-6"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#b99655]">{item.category}</p><h3 className="display mt-3 text-3xl">{item.title}</h3><p className="mt-3 text-slate-600">{item.summary}</p></article>)}</div></div></section>
      <section className="section-pad bg-white"><div className="container"><p className="eyebrow text-[#b99655]">Compliance Calendar</p><h2 className="section-title">Key statutory reminders.</h2><div className="mt-10 overflow-hidden rounded-3xl border border-slate-200">{complianceCalendar.slice(0, 4).map((item) => <div key={`${item.date}-${item.task}`} className="grid gap-3 border-b border-slate-200 p-6 last:border-b-0 md:grid-cols-[220px_1fr_160px]"><strong>{item.date}</strong><span className="text-slate-600">{item.task}</span><span className="text-sm font-semibold text-[#b99655]">{item.owner}</span></div>)}</div><Link href="/compliance-calendar" className="mt-7 inline-flex font-bold text-[#b99655]">View full calendar →</Link></div></section>
      <Faq />
    </main>
  );
}
