import type { Metadata } from 'next';
import { AssetImage } from '../../components/AssetImage';
import { Breadcrumbs } from '../../components/Breadcrumbs';
import { PageHero } from '../../components/PageHero';
import Link from 'next/link';
import { locationPages, offices, site } from '../../lib/content';

export const metadata: Metadata = { title: 'Offices in Bapatla, Guntur and Hyderabad', description: 'Regional office coordination for Minchala & Associates in Bapatla, Guntur and Hyderabad. Meetings are by appointment.' };

export default function OfficesPage() {
  const localBusinessJsonLd = offices.map((office) => ({ '@context': 'https://schema.org', '@type': 'LocalBusiness', name: `${site.name} ${office.city}`, url: site.url, email: site.email, address: { '@type': 'PostalAddress', addressLocality: office.city, addressRegion: office.region, addressCountry: 'IN' } }));
  return <main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessJsonLd) }} /><Breadcrumbs items={[{ label: 'Offices' }]} /><PageHero eyebrow="Office locations" title="Regional access across Andhra Pradesh and Telangana." description="Client meetings are coordinated by appointment and subject to engagement scope, professional eligibility and availability." /><section className="section-pad"><div className="container grid gap-6 md:grid-cols-3">{offices.map((office) => <article key={office.city} className="luxury-card overflow-hidden rounded-3xl"><AssetImage {...office.image} width={900} height={560} className="h-56 w-full object-cover" /><div className="p-7"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#b99655]">{office.region}</p><h2 className="display mt-2 text-4xl">{office.city}</h2><p className="mt-3 leading-7 text-slate-600">{office.address}</p><p className="mt-3 text-sm leading-7 text-slate-500">{office.focus}</p><div className="mt-6 flex flex-wrap gap-3"><a className="inline-flex font-bold text-[#b99655]" href={office.mapHref} rel="noopener noreferrer" target="_blank">Open map search →</a><Link className="inline-flex font-bold text-[#0b2433]" href={`/locations/${office.city.toLowerCase()}`}>Local SEO page →</Link></div></div></article>)}</div></section><section className="section-pad bg-white"><div className="container"><p className="eyebrow text-[#b99655]">Location pages</p><h2 className="section-title max-w-4xl">Dedicated local information for Bapatla, Guntur and Hyderabad.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{locationPages.map((location) => <Link key={location.slug} href={`/locations/${location.slug}`} className="luxury-card rounded-3xl p-6"><h2 className="display text-3xl">{location.title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{location.description}</p></Link>)}</div></div></section></main>;
}
